name: Build and deploy ASP app to Azure Web App - money-map-expense-tracker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore "ExpenseTracker.sln"

      - name: Build project
        run: dotnet build "ExpenseTracker.sln" --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish "ExpenseTracker.sln" --configuration Release --output ./publish --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: asp-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: asp-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1AA75FA4FC044E5C9C8D5E432CE19993 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5199EAEA4AD6491DB10A4F8F7DB119C9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_81DB7CA3E1C64596BCA23F298C8AF3E8 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'money-map-expense-tracker'
          slot-name: 'Production'
          package: .
